version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: always
    ports: 
      - "9091:1972"
      - "9092:52773"
      - ${IRIS_PORT}:52773

    
    network_mode: "alpine-net"

    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app